name = "cloudflare-next"
compatibility_date = "2025-03-25"

[build]
command = "npx --yes n@20.10.0 && npm run build && npx @cloudflare/next-on-pages"

[site]
bucket = ".vercel/output"

[env.production]
node_compat = true
compatibility_flags = ["nodejs_compat"]
node_version = "20.10.0" # Or the latest supported version
